function tripcolor_custom(ax, nodes, elems, fvals)
% Simple element-constant colour plot using patch().
    patch('Parent', ax, ...
          'Faces', elems, ...
          'Vertices', nodes, ...
          'FaceVertexCData', fvals, ...
          'FaceColor', 'flat', ...
          'EdgeColor', 'none');
    colormap(ax, 'jet');
end


